package com.example.project.entities.enums;

import lombok.Getter;
import lombok.RequiredArgsConstructor;

@Getter
@RequiredArgsConstructor
public enum Permission {
    TENANT_CREATE("TENANT_CREATE"),
    TENANT_READ("TENANT_READ"),
    TENANT_UPDATE("TENANT_UPDATE"),
    TENANT_DELETE("TENANT_DELETE"),
    FLAT_SEARCH("FLAT_SEARCH"),
    BOOKING_CREATE("BOOKING_CREATE"),
    BOOKING_READ("BOOKING_READ"),
    BOOKING_CANCEL("BOOKING_CANCEL"),

    OWNER_CREATE("OWNER_CREATE"),
    OWNER_READ("OWNER_READ"),
    OWNER_UPDATE("OWNER_UPDATE"),
    FLAT_CREATE("FLAT_CREATE"),
    FLAT_UPDATE("FLAT_UPDATE"),
    FLAT_DELETE("FLAT_DELETE"),
    FLAT_READ("FLAT_READ"),
    BOOKING_UPDATE("BOOKING_UPDATE"),

    ADMIN_REGISTER("ADMIN_REGISTER"),
    ADMIN_READ("ADMIN_READ"),
    ADMIN_MANAGE_USERS("ADMIN_MANAGE_USERS"),
    ADMIN_MANAGE_FLATS("ADMIN_MANAGE_FLATS"),
    ADMIN_MANAGE_BOOKINGS("ADMIN_MANAGE_BOOKINGS"),
    ADMIN_DELETE_USERS("ADMIN_DELETE_USERS"),
    REPORTS_GENERATE("REPORTS_GENERATE");

    private final String permission;
}
